plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.3' apply false
}

group = 'com.kubota6646'
version = '2.5.1'

subprojects {
    apply plugin: 'java'
    apply plugin: 'com.gradleup.shadow'
    
    group = rootProject.group
    version = rootProject.version
    
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    
    repositories {
        mavenCentral()
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'sonatype'
            url = 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
        maven {
            name = 'jitpack'
            url = 'https://jitpack.io'
        }
    }
    
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
